module parser

import os
import v.flat
import v.token

struct VmlLocation {
	path   string
	line   int = 1
	column int = 1
}

fn (mut c VmlCompiler) writeln(line string) {
	c.out.writeln(line)
	for _ in 0 .. line.count('\n') + 1 { c.locations << c.location }
}

// Keep generated byte offsets: V uses lexical ordering to resolve comptime
// local initializers. Logical source directives provide VML locations without
// collapsing declarations and their uses onto the same physical position.
fn (mut p Parser) remap_vml_source(first_node int, first_diagnostic int, locations []VmlLocation) {
	mut mapped := map[int]bool{}
	for index in first_node .. p.a.nodes.len {
		node := p.a.nodes[index]
		mut file := p.a.source_files[node.pos.id] or { continue }
		if node.pos.id !in mapped {
			if file.name != '<veb-template>' { continue }
			for line_index in 1 .. locations.len {
				if line_index >= file.line_count() { break }
				location := locations[line_index]
				file.add_line_directive(file.line_start(line_index), location.line, location.path)
			}
			mapped[node.pos.id] = true
		}
		line_index := file.position(node.pos).line - 1
		if line_index >= 0 && line_index < locations.len && node.pos.type_text_id() == 0 {
			p.a.nodes[index] = flat.Node{ ...node, pos: node.pos.with_reported_column(locations[line_index].column) }
		}
	}
	for index in first_diagnostic .. p.diagnostics.len {
		diagnostic := p.diagnostics[index]
		file := p.a.source_files[diagnostic.pos.id] or { continue }
		if diagnostic.pos.id !in mapped { continue }
		line_index := file.position(diagnostic.pos).line - 1
		if line_index < 0 || line_index >= locations.len { continue }
		location := locations[line_index]
		p.diagnostics[index] = Diagnostic{ ...diagnostic, file: location.path, line: location.line, column: location.column, pos: diagnostic.pos.with_reported_column(location.column) }
	}
}

// Generic guards let V validate declared list and key types even for empty lists.
// They have no runtime effects and reuse the language's normal type checker.
fn (mut c VmlCompiler) write_list_guard(value string, suffix string, array bool) {
	name := '${c.guard_prefix}_${suffix}_' + if array { 'array' } else { 'key' }
	c.guards << VmlGuard{ name: name, array: array, location: c.location }
	c.writeln('\tif false { ${name}(${value}) }')
}

fn (mut c VmlCompiler) write_field_guard(value string, field_name string, model_path string) {
	name := '${c.guard_prefix}_field_${c.guards.len}'
	c.guards << VmlGuard{ name: name, field_name: field_name, model_path: model_path, location: c.location }
	c.writeln('\tif false { ${name}(${value}) }')
}

fn (mut c VmlCompiler) write_list_guards() {
	for guard in c.guards {
		c.location = guard.location
		c.writeln('fn ${guard.name}[T](value T) {')
		c.writeln('\t_ = value')
		if guard.field_name.len > 0 {
			// Reflection marks interface fields as private although they are public contracts.
			// Follow pointer schemas without reading a value: these guards are never executed.
			c.writeln('\t$if T is $pointer { ${guard.name}(unsafe { *value }) } $else $if T !is $interface {')
			c.writeln('\t\t$for field in T.fields {')
			c.writeln('\t\t\t$if field.name == ${vml_quote(guard.field_name)} {')
			c.writeln('\t\t\t\t$if !field.is_pub { $compile_error(' + vml_quote('VML model path `${guard.model_path}` must use public fields') + ') }')
			c.writeln('\t\t\t}')
			c.writeln('\t\t}')
			c.writeln('\t}')
		} else if guard.array {
			c.writeln("\t$if T !is $array { $compile_error('Repeater model must be an array') }")
		} else {
			c.writeln("\t$if T !is string && T !is $int && T !is $float && T !is bool { $compile_error('Repeater key must be a scalar value') }")
		}
		c.writeln('}')
	}
}

fn (mut p Parser) register_vml_source(path string, source string, call_pos token.Pos) int {
	mut files := token.FileSet.new()
	mut file := files.add_file(path, source.len)
	file.index_lines(source)
	id := p.next_file_id
	p.next_file_id++
	p.a.source_files[id] = file
	p.a.template_call_sites[id] = call_pos
	p.a.template_actions[id] = p.template_action_name()
	return id
}

fn (mut p Parser) record_vml_diagnostic(path string, source string, message string, call_start int) {
	mut diagnostic_path := path
	mut diagnostic_source := source
	mut text := message.all_before_last(' at line ')
	location := message.all_after_last(' at line ')
	mut line := int_max(1, location.all_before(',').int())
	mut column := int_max(1, location.all_after('column ').int())
	parts := message.split(':')
	if parts.len >= 4 && parts[1].int() > 0 && parts[2].int() > 0 {
		diagnostic_path = parts[0]
		diagnostic_source = os.read_file(diagnostic_path) or { source }
		line = parts[1].int()
		column = parts[2].int()
		text = parts[3..].join(':').trim_space()
	}
	id := p.register_vml_source(diagnostic_path, diagnostic_source, p.span_to(call_start))
	file := p.a.source_files[id] or { return }
	start := int_min(diagnostic_source.len, file.line_start(line) + column - 1)
	p.append_diagnostic(Diagnostic{
		file:    diagnostic_path
		pos:     token.new_span(id, start, int_min(diagnostic_source.len, start + 1))
		line:    line
		column:  column
		message: text
	})
}
